Test deb releases

diff --git a/.github/workflows/deb_release.yml b/.github/workflows/deb_release.yml
--- a/.github/workflows/deb_release.yml
+++ b/.github/workflows/deb_release.yml
@@ -1,14 +1,17 @@
 name: Deb Release
 run-name: |
-  deb release [${{github.ref_name}}]
+  deb release [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}]
 
 on:
   workflow_dispatch:
 
   push:
     tags:
-      - '*'
-      - '!*/**'
+      - 'debian/*'
+
+  workflow_run:
+    workflows: ["Release (default)"]
+    types: [completed]
 
 concurrency:
   group: deb-release-${{ github.ref }}
@@ -19,94 +22,52 @@ permissions:
   packages: read
 
 jobs:
-  build-packages:
-    strategy:
-      matrix:
-        builder-tag: ["ubuntu-22.04"]
+  check-trigger:
+    if: github.event_name == 'workflow_run'
     runs-on: ubuntu-latest
+    outputs:
+      DO_BUILD: ${{steps.config.outputs.DO_BUILD}}
     steps:
-    - name: Clone uno
-      uses: actions/checkout@v4
-      with:
-        path: src/uno
-        submodules: true
+      - name: "Generate test configuration"
+        id: config
+        run: |
+          do_build=y
+          case "${{github.ref_type}}" in
+            tag)
+              ;;
+            branch)
+              case "${{github.ref_name}}" in
+                master)
+                  ;;
+                *)
+                do_build=
+                  ;;
+              esac
+              ;;
+          esac
+          (
+            echo DO_BUILD=${do_build}
+          ) >> ${GITHUB_OUTPUT}
+      - name: "Fail if upstream job failed"
+        run: |
+          echo "upstream job for ${{github.ref_type}} ${{github.ref_name}} failed with conclusion '${{github.event.workflow_run.conclusion}}'"
+          exit 1
+        if: steps.config.outputs.DO_BUILD && github.event.workflow_run.conclusion != 'success'
 
-    - name: Log in to GitHub
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Build packages
-      run: |
-        docker run --rm \
-          --pull always \
-          -v $(pwd)/src/uno:/uno \
-          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
-          /uno/scripts/debian_build.sh
-
-    - name: Fix permissions
-      run: |
-        docker run --rm \
-          -v $(pwd)/src/uno:/uno \
-          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
-          chown -R $(id -u):$(id -g) /uno
-      if: always()
-
-    - name: Upload uno packages
-      uses: actions/upload-artifact@v4
-      with:
-        name: uno
-        path: src/uno/debian-dist/uno_*
-
-
-  build-packages-arm64:
+  build-packages:
+    needs: check-trigger
+    if: needs.check-trigger.outputs.DO_BUILD
     strategy:
       matrix:
-        builder-tag: ["ubuntu-22.04"]
-    runs-on: ["self-hosted", "linux", "arm64", "rpi5"]
-    steps:
-    - name: Clone uno
-      uses: actions/checkout@v4
-      with:
-        path: src/uno
-        submodules: true
-
-    - name: Log in to GitHub
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Build packages
-      run: |
-        docker run --rm \
-          --pull always \
-          -v $(pwd)/src/uno:/uno \
-          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
-          /uno/scripts/debian_build.sh
-
-    - name: Fix permissions
-      run: |
-        docker run --rm \
-          -v $(pwd)/src/uno:/uno \
-          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
-          chown -R $(id -u):$(id -g) /uno
-      if: always()
-
-    - name: Upload uno packages
-      uses: actions/upload-artifact@v4
-      with:
-        name: uno-arm64
-        path: src/uno/debian-dist/uno_*
-
+        base-tag: ["ubuntu:22.04"]
+        platform: [amd64, arm64]
+    uses: ./.github/workflows/_deb_build.yml
+    with:
+      base-tag: ${{ matrix.base-tag }}
+      platform: ${{ matrix.platform }}
 
   publish_release:
-    needs:
-      - build-packages
-      - build-packages-arm64
+    needs: build-packages
     if: github.ref_type == 'tag'
     runs-on: ubuntu-latest
     steps:
